version: 1.4.0.{build}

image: Previous Visual Studio 2017

branches:
  except:
    - gh-pages

skip_tags: true

skip_commits:
  message: \[(ci skip|skip ci)\].*

clone_depth: 50

test: off

build_script:
- cmd: dotnet restore
- cmd: dotnet test ./tests/FsRandom.Tests/FsRandom.Tests.fsproj
- cmd: dotnet test ./tests/FsRandom.Tests.CSharp/FsRandom.Tests.CSharp.csproj
