//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsRandom.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KnownRandomSequence {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KnownRandomSequence() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FsRandom.Tests.Resources.KnownRandomSequence", typeof(KnownRandomSequence).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000 outputs of genrand64_int64()
        /// 7266447313870364031  4946485549665804864 16945909448695747420 16394063075524226720  4873882236456199058 
        ///14877448043947020171  6740343660852211943 13857871200353263164  5249110015610582907 10205081126064480383 
        /// 1235879089597390050 17320312680810499042 16489141110565194782  8942268601720066061 13520575722002588570 
        ///14226945236717732373  9383926873555417063 15690281668532552105 11510704754157191257 15864264574919463609 
        /// 6489677788245343319  5112602299894754389 108289300626 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mt19937_64_out {
            get {
                return ResourceManager.GetString("mt19937_64_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000 outputs of genrand_int32()
        ///1067595299  955945823  477289528 4107218783 4228976476 
        ///3344332714 3355579695  227628506  810200273 2591290167 
        ///2560260675 3242736208  646746669 1479517882 4245472273 
        ///1143372638 3863670494 3221021970 1773610557 1138697238 
        ///1421897700 1269916527 2859934041 1764463362 3874892047 
        ///3965319921   72549643 2383988930 2600218693 3237492380 
        ///2792901476  725331109  605841842  271258942  715137098 
        ///3297999536 1322965544 4229579109 1395091102 3735697720 
        ///2101727825 3730287744 2950434330 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mt19937ar_out {
            get {
                return ResourceManager.GetString("mt19937ar_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFMT-11213:68-14-3-7-3:effff7fb-ffffffef-dfdfbfff-7fffdbfd
        ///32 bit generated randoms
        ///init_gen_rand__________
        /// 553293926  698755237 2442073441 4209880924 1764362329 
        ///2195309918  256824928 2214706803 2136320427 2843087932 
        ///3486529899 1306350756 4270642900 3297631664 1850831330 
        ///4213109783  427081536 1131131307 2775965886  877546999 
        ///2836645597 2850507086 2755759911 1306876265 2575673187 
        ///1824065691 3511080041 1928485268  649052443 2971742730 
        /// 403698108  169875003  380295356 3528011866 2952256661 
        ///3733745051 4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SFMT_11213_out {
            get {
                return ResourceManager.GetString("SFMT_11213_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFMT-1279:7-14-3-5-1:f7fefffd-7fefcfff-aff3ef3f-b5ffff7f
        ///32 bit generated randoms
        ///init_gen_rand__________
        /// 243307689 3927268025 1225611617  570598983 3842545525 
        ///2650524507 1977115969 1192210573 3351391148 3300947918 
        ///3372624199 3407802072 2630055668 1419320069 1694567123 
        /// 363293933 1331811503 3765039298 3154732976 1386095844 
        ///2088338954 3179212843 1879834946 1381367989 2758426993 
        ///3290922490  459138429 2772088455  284265626  697699287 
        ///2148849595  828780633 3291316348  576422791  275230034 
        ///1474356354 372 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SFMT_1279_out {
            get {
                return ResourceManager.GetString("SFMT_1279_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFMT-132049:110-19-1-21-1:ffffbb5f-fb6ebf95-fffefffa-cff77fff
        ///32 bit generated randoms
        ///init_gen_rand__________
        ///3596981943 2237974425 3827224957 2514757895 4264843680 
        /// 955444628 1982846266 3690734264 2164407755 2213046834 
        ///1724693857   51549213 1214613897  969393410 3593568815 
        ///3968248172  732457991 4110147364 2568450099  111613531 
        ///3105149926 3474245237 3165871412 1276608804 3923836977 
        ///3648769445  756375000 3003259904 3475051552 3064994508 
        ///1738060392 1253564194  436357404 3649391826 1996013715 
        ///272902139 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SFMT_132049_out {
            get {
                return ResourceManager.GetString("SFMT_132049_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFMT-19937:122-18-1-11-1:dfffffef-ddfecb7f-bffaffff-bffffff6
        ///32 bit generated randoms
        ///init_gen_rand__________
        ///3440181298 1564997079 1510669302 2930277156 1452439940 
        ///3796268453  423124208 2143818589 3827219408 2987036003 
        ///2674978610 1536842514 2027035537 2534897563 1686527725 
        /// 545368292 1489013321 1370534252 4231012796 3994803019 
        ///1764869045  824597505  862581900 2469764249  812862514 
        /// 359318673  116957936 3367389672 2327178354 1898245200 
        ///3206507879 2378925033 1040214787 2524778605 3088428700 
        ///1417665896 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SFMT_19937_out {
            get {
                return ResourceManager.GetString("SFMT_19937_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFMT-216091:627-11-3-10-1:bff7bff7-bfffffff-bffffa7f-ffddfbfb
        ///32 bit generated randoms
        ///init_gen_rand__________
        ///1905350899  752275649 2172726721 1382267163 3279518050 
        ///3268632728 3717363760 4072571273 1344655483  219752927 
        /// 511254305 3596362759 4226641704 4129438728  558485682 
        ///1317634157 4010378104 3580397823 1818301359 3313744323 
        ///1311807646 3802672028 2808584435 3266301975 2020171045 
        /// 620506054   53161800 1537320991 2134803893 2715479037 
        /// 120112962 2441794334 1814983540 1206486557 4161448945 
        ///236604955 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SFMT_216091_out {
            get {
                return ResourceManager.GetString("SFMT_216091_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFMT-2281:12-19-1-5-1:bff7ffbf-fdfffffe-f7ffef7f-f2f7cbbf
        ///32 bit generated randoms
        ///init_gen_rand__________
        /// 816899028 2529810904 2984700728 4161010272 3805350266 
        ///1279614432  425690784 1116614207 1104668239 1157865543 
        ///2631428793 1738783324 3817657585 4038396021 3929248340 
        ///2632374408 3059467376 1178391445 1548683528 2345690040 
        ///2324785226 3565094863 2477561011 3810275196 2224650186 
        ///3954132583 2271684514 3280953479 3453754330 1876516579 
        ///3970777246 2889125929 2780400968 2196210122 1644459300 
        ///3635678387 12 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SFMT_2281_out {
            get {
                return ResourceManager.GetString("SFMT_2281_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFMT-4253:17-20-1-7-1:9f7bffff-9fffff5f-3efffffb-fffff7bb
        ///32 bit generated randoms
        ///init_gen_rand__________
        ///2527479900 1368357778 2663671614 1404435254 2699472814 
        ///  90613554  184715818  548052880 3165295246 3747208322 
        ///1553584151 4006205422  686873885 2973265227  338288274 
        /// 840903586  118479351 2113933085 2454705318 4160313692 
        /// 258320158 2069535581 3111482672 1808812962 1061444454 
        ///3414467438 2429935983   22860572 1366710514 3914109077 
        /// 431345992 2592701388 4278051019 2953043318 3980401588 
        ///3881325187 15 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SFMT_4253_out {
            get {
                return ResourceManager.GetString("SFMT_4253_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFMT-44497:330-5-3-9-3:effffffb-dfbebfff-bfbf7bef-9ffd7bff
        ///32 bit generated randoms
        ///init_gen_rand__________
        ///3668471065 3938124162 4226228648 1183164762  959305109 
        ///2236634761 1737928337 1068590968 3291811912  438989883 
        ///3781999933 3563472944 2602217062 3696065256 4239318581 
        /// 600000730  307966818    9789691 3596262746 4049798863 
        /// 214000891 2824657360 3401599604 4084185957  241354882 
        ///2606104362 3350316152 1210189242  956851300  428314233 
        ///3496239949 2553393773  715503161 1503533865 2409071411 
        ///3720288303 3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SFMT_44497_out {
            get {
                return ResourceManager.GetString("SFMT_44497_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFMT-607:2-15-3-13-3:fdff37ff-ef7f3f7d-ff777b7d-7ff7fb2f
        ///32 bit generated randoms
        ///init_gen_rand__________
        ///1196421539 2865311212 3866479472 2692900087 3838928621 
        ///3188765817 2751632982 3712143069  549918413 2026167923 
        ///1600383423 1164248707 3597250909 1646078700 3597866549 
        /// 738391729 1195673494  320418194 3419357688 4060638541 
        ///3132037965 2907853147  886556822 1640020536 2638235623 
        /// 538643813  513603633 1576774846 2624061267 1520310145 
        ///1556074285  274920712 1875395000  435607661 4280948541 
        ///3881013247 187 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SFMT_607_out {
            get {
                return ResourceManager.GetString("SFMT_607_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFMT-86243:366-6-7-19-1:fdbffbff-bff7ff3f-fd77efff-bf9ff3ff
        ///32 bit generated randoms
        ///init_gen_rand__________
        /// 729010956 4245516629 2851064434  363057815 4150273260 
        /// 802798522  976169071 3393068005 3351056475 2112374092 
        ///2951503395   75264394 3725198372 3171075061 4054667720 
        ///1970282238 2826304822  103324300 1192438872 1645653767 
        ///3276917106 1837939138 3134877800 2607296330 1268482729 
        ///2287079542 1979339044 1955581610  881350673 1823446539 
        ///4048330951 3240075473  118504416  129971735 3591962661 
        ///2091536776  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SFMT_86243_out {
            get {
                return ResourceManager.GetString("SFMT_86243_out", resourceCulture);
            }
        }
    }
}
